# Generated by Django 6.0.5 on 2026-07-06 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interviews', '0003_answer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='audio_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='interview',
            name='score',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
